// Date: 2/4/2015 3:14:38 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.totallyminecraft.superblocks.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelFlatStairs extends ModelBase
{
  //fields
    ModelRenderer BottomStep;
    ModelRenderer TopStep;
  
  public ModelFlatStairs()
  {
    textureWidth = 64;
    textureHeight = 64;
    
      BottomStep = new ModelRenderer(this, 0, 0);
      BottomStep.addBox(0F, 0F, 0F, 16, 1, 8);
      BottomStep.setRotationPoint(-8F, 16F, -8F);
      BottomStep.setTextureSize(64, 64);
      BottomStep.mirror = true;
      setRotation(BottomStep, 0F, 0F, 0F);
      TopStep = new ModelRenderer(this, 0, 0);
      TopStep.addBox(0F, 0F, 0F, 16, 1, 8);
      TopStep.setRotationPoint(-8F, 8F, 0F);
      TopStep.setTextureSize(64, 64);
      TopStep.mirror = true;
      setRotation(TopStep, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    BottomStep.render(f5);
    TopStep.render(f5);
  }

  public void renderModel(float f){
    BottomStep.render(f);
    TopStep.render(f);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
